name: Deploy Payload

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Server Update Webhook
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${{ secrets.DEPLOY_API_KEY }}" \
          ${{ secrets.API_BASE_URL }}/api/update
